### ISSUE TITLE
negative background not working inside minor_button_group

### ISSUE THREAD

**Issue by etdsoft** [thetron/css3buttons_rails_helpers#14] opened 2011-06-03 12:21 UTC
This doesn't result in red background on :hover for the last link

```
    <% minor_button_group do -%>
      <%= pill_button_link_to 'Show', project %>
      <%= edit_pill_button_link_to 'Edit', edit_project_path(project) %>
      <%= remove_negative_pill_button_link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %>
   <% end -%>
```

This does:

```
    <% button_group do -%>
      <%= pill_button_link_to 'Show', project %>
      <%= edit_pill_button_link_to 'Edit', edit_project_path(project) %>
      <%= remove_negative_pill_button_link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %>
   <% end -%>
```

**Comment by thetron** [comment] 2011-06-04 06:24
Thanks for reporting this, but I'm reasonably certain this is by design - but I'm not completely sure, since I didn't design the CSS. I'm using [this CSS library](http://nicolasgallagher.com/lab/css3-github-buttons/), which as of the current version - just makes the text red when using a negative (danger) button inside a minor button group.

That being said, I would tend to agree that on hover it _should_ be red. The next version of the gem, will include things like missing colours for positive/safe buttons - and I may include a fix for this too.

**Closed as completed** 2011-10-03 02:03 UTC
